### ISSUE TITLE
v4 Roadmap

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#118]
These are the tentative list of breaking changes we should be looking to introduce in v4 and improve the package.

- [ ] useBoundingClientRect with `update` to support external events and recalculate
- [ ] useHookRef for all useHook which take a ref as argument. It can be useful if the ref is also returned by the hook itself. Eg 
`const [ref, value] = useBoundingClientRectRef()` 
`const [ref] = useOutsideClickRef(cb)` 
`const [ref] = useOutsideClickRef(cb)` 
- [ ] Move to array destructuring and simplify return values for most hooks.
- [ ] useForkRef to support callback refs and mutable refs
- [ ] _More to come_
